name: "Build Pipeline"

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  UV_VERSION: "0.11.7"
  RUFF_VERSION: "0.14.2"
  PYRIGHT_VERSION: "1.1.409"
  SRC_DIR: "./rt_opt"

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          version: ${{ env.UV_VERSION }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run ruff
        uses: astral-sh/ruff-action@v4.0.0
        with:
          src: ${{ env.SRC_DIR }}
          version: ${{ env.RUFF_VERSION }}

      - name: Run pyright
        uses: jakebailey/pyright-action@v3
        with:
          version: ${{ env.PYRIGHT_VERSION }}
          working-directory: ${{ env.SRC_DIR }}

  version-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          version: ${{ env.UV_VERSION }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run unit tests
        run: |
          uv run pytest -v -m "not regression"