name: "Build Pipeline"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  UV_VERSION: "0.11.7"
  RUFF_VERSION: "0.14.2"
  PYRIGHT_VERSION: "1.1.409"
  PREFERRED_PYTHON_VERSION: "3.13"

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ env.PREFERRED_PYTHON_VERSION }}
          version: ${{ env.UV_VERSION }}

      - name: Install dependencies
        run: uv sync --extra dev --extra demo

      - name: Run ruff
        uses: astral-sh/ruff-action@v4.0.0
        with:
          version: ${{ env.RUFF_VERSION }}

      - name: Run pyright
        uses: jakebailey/pyright-action@v3
        with:
          version: ${{ env.PYRIGHT_VERSION }}

  version-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          version: ${{ env.UV_VERSION }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run unit tests
        # Run the tests with coverage only with the preferred Python version, to avoid
        # unnecessary multiple coverage runs.
        run: |
          if [ "${{ matrix.python-version }}" = "${{ env.PREFERRED_PYTHON_VERSION }}" ]; then
            uv run pytest -v -m "not regression" --cov=rt_opt --cov-report=json
          else
            uv run pytest -v -m "not regression"
          fi

      - name: Run regression tests
        # Run regression tests only for the preferred Python version.
        if: ${{ matrix.python-version == env.PREFERRED_PYTHON_VERSION }}
        run: |
          uv run pytest -v -m regression

      - name: Update Coverage Badge
        # Only update the coverage badge for the preferred Python version and on master.
        if: ${{ matrix.python-version == env.PREFERRED_PYTHON_VERSION && github.ref == 'refs/heads/master' }}
        uses: we-cli/coverage-badge-action@main